dist: trusty
sudo: required
language: cpp
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_install:
  - ./build_toolchain

install:
  - ./cmake_run

script:
  - ./make_run tests
