
notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      env: RELEASE=on
      addons:
        apt:
          packages:
            - nasm
            - qemu

    - os: linux
      dist: trusty
      sudo: required
      language: generic
      env: RELEASE=off USE_GCOV=on
      addons:
        apt:
          packages:
            - nasm
            - qemu

before_install:
  - ./scripts/build_toolchain --skip-install-pkgs
  - ./scripts/build_toolchain -s download_i686_toolchain


install:
  - make
  - make gtests

script:
  - ./build/gtests
  - ./scripts/generate_coverage_report # Does nothing if not USE_GCOV.
  - ./system_tests/run_system_test

