
notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      env: RELEASE=on
      addons:
        apt:
#         sources:
#           - ubuntu-toolchain-r-test
          packages:
            - gcc-multilib
            - nasm
            - binutils-multiarch
            - mtools
            - qemu

    - os: linux
      dist: trusty
      sudo: required
      language: generic
      env: RELEASE=off USE_GCOV=on
      addons:
        apt:
#         sources:
#           - ubuntu-toolchain-r-test
          packages:
            - gcc-multilib
            - nasm
            - binutils-multiarch
            - mtools
            - qemu

before_install:
  - ./scripts/build_toolchain --skip-install-pkgs

install:
  - make
  - make gtests

script:
  - ./build/gtests
  - ./scripts/generate_coverage_report # Does nothing if not USE_GCOV.
  - ./system_tests/run_system_test

