
notifications:
  email:
    on_success: never
    on_failure: always

# In order to ask travis to install packages:
# sudo: required AND under matrix/include:
# addons:
#   apt:
#     packages:
#       - qemu-system-x86
# [ at the same level of env ]

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      env: RELEASE=1
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      env: RELEASE=0 USE_GCOV=on
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      env: RELEASE=0 CXX=clang++


before_install:
  - ./scripts/build_toolchain --skip-install-pkgs

install:
  - make -j
  - make -j gtests

script:
  - MALLOC_CHECK_=2 ./build/gtests
  - ./scripts/generate_coverage_report # Does nothing if not USE_GCOV.


