dist: trusty
sudo: required
language: cpp
os:
  - linux

before_install:
  - mkdir temp
  - cd temp
  - wget https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz
  - tar xf cmake-3.7.2.tar.gz
  - cd cmake-3.7.2
  - ./configure
  - make
  - make install
  - cd ../..
  - ./build_toolchain

install:
  - ./cmake_run

script:
  - ./make_run tests
