
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: RELEASE=on
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-6-multilib
            - g++-6-multilib

    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: RELEASE=off USE_GCOV=on
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-6-multilib
            - g++-6-multilib

before_install:
  - ./build_toolchain

install:
  - ./cmake_run
  - ./make_run
  - ./make_run tests

script:
  - ./build/tests
  - ./generate_coverage_report # Does nothing unless USE_GCOV is set
